apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headspace-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: www.headspace-ai.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: headspace-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headspace-frontend
            port:
              number: 3000
