import logging
from typing import Dict, Any
from app.schemas.wellness import WellnessEngineOutput
from app.schemas.safety import RiskLevel

logger = logging.getLogger(__name__)

class SafetyValidator:
    """
    Ensures that recommendations generated by the Wellness Engine are safe to present to the user.
    """
    
    @staticmethod
    def validate(output: WellnessEngineOutput, state: Dict[str, Any]) -> WellnessEngineOutput:
        """
        Validates the output against the current risk assessment.
        If the risk is High or Emergency, most generative recommendations should be restricted.
        """
        risk_dict = state.get("risk_assessment", {})
        risk_level = risk_dict.get("risk_level", RiskLevel.LOW) if risk_dict else RiskLevel.LOW
        
        if risk_level in [RiskLevel.HIGH, RiskLevel.EMERGENCY]:
            logger.warning(f"SafetyValidator: Rejecting generative wellness recommendations due to {risk_level} risk.")
            # Clear out potentially harmful generative advice
            output.recommendations = []
            output.action_plan = []
            output.reasoning = "System safety override: User is in distress. Standard generative recommendations are suppressed."
            output.follow_up_questions = ["Would you like to try a grounding exercise?", "Can I provide some support resources?"]
            
        return output
